# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
notifications:
  email: false
git:
  depth: 10
language: c

addons:
  apt:
    packages: &hb-linux-common
      - firebird2.5-dev
    # - libcairo2-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libfreeimage-dev
      - libgd2-xpm-dev
      - libgpm-dev
    # - libgs-dev
      - libicu-dev
      - libmagic-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpq-dev
    # - libslang2-dev
      - unixodbc-dev

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
      env: [ HB_CI_THREADS=4, HB_CCSUFFIX=-4.0 ]
      addons:
        apt:
          packages: [ *hb-linux-common, clang-4.0 ]
          sources: llvm-toolchain-trusty-4.0
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env: [ HB_CI_THREADS=4, HB_CCSUFFIX=-6 ]
      addons:
        apt:
          packages: [ *hb-linux-common, gcc-6, g++-6 ]
          sources: ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      # https://hub.docker.com/_/ubuntu/
      env: [ HB_CI_THREADS=4, PKG_SUFFIX=linux, 'DOCKER_IMAGE=ubuntu:rolling' ]
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: HB_CI_THREADS=4
    - os: osx
      osx_image: xcode8.2
      compiler: i686-w64-mingw32-gcc
      env: [ HB_CI_THREADS=4, PKG_SUFFIX=mac ]

before_install:
  - >
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
        time brew install p7zip mingw-w64 jq osslsigncode dos2unix gpg coreutils || true
        time brew install --force-bottle --build-bottle wine || true
        export MXE_DONT_INSTALL=gcc
        time ./package/mpkg_win_dl_mxe.sh \
          mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql} \
          mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd}
      else
        brew install cairo curl freeimage gd ghostscript icu4c libmagic mariadb openssl@1.1 qt5 s-lang unixodbc
      fi
      export MACOSX_DEPLOYMENT_TARGET=10.10
    elif [ -n "${DOCKER_IMAGE}" ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "${PWD}:${PWD}" -w "${PWD}" \
        --env-file <(env | grep -E '^(TRAVIS_|HB_)') \
        "${DOCKER_IMAGE}" \
        sh -c ./package/mpkg_win_docker.sh
    fi

script:
  - >
    if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      if [ -z "${DOCKER_IMAGE}" ]; then
        ./package/mpkg_win_ci.sh
      fi
      [ -f harbour-snapshot-win.7z ] && mv -f harbour-snapshot-win.7z "harbour-snapshot-win-built-on-${PKG_SUFFIX}.7z"
    else
      ls -lA "$(dirname "$(which "${CC}${HB_CCSUFFIX}")")/${CC}"*
      "${CC}${HB_CCSUFFIX}" -v
      HB_COMPILER=$CC make -j "${HB_CI_THREADS}"
    fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: harbour-snapshot-win-built-on-${PKG_SUFFIX}.7z
  file_glob: false
  tag_name: v3.4.0dev
  draft: false
  prerelease: true
  overwrite: true
  on:
    branch: master
    condition: "$CC = i686-w64-mingw32-gcc"
