notifications:
  email: false
git:
  depth: 10
os: osx

before_install:
  - time travis_retry brew update || true
  - time travis_retry brew install --force-bottle --build-bottle wine || true
  - export DISPLAY=
  - time wineboot

script:
  - echo Done.
