# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
language: c
addons:
  apt:
    packages: &hb-linux-common
      - firebird2.5-dev
    # - libcairo2-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libfreeimage-dev
      - libgd2-xpm-dev
      - libgpm-dev
    # - libgs-dev
      - libicu-dev
      - libmagic-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpq-dev
    # - libslang2-dev
      - unixodbc-dev
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
      env: [ HB_CI_THREADS=4, HB_CCSUFFIX=-3.9 ]
      addons:
        apt:
          packages: [ *hb-linux-common, clang-3.9 ]
          sources: llvm-toolchain-trusty-3.9
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env: [ HB_CI_THREADS=4, HB_CCSUFFIX=-6 ]
      addons:
        apt:
          packages: [ *hb-linux-common, gcc-6, g++-6 ]
          sources: ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      env: HB_CI_THREADS=4
      addons:
        apt:
          packages:
            - [ binutils-mingw-w64, gcc-mingw-w64, g++-mingw-w64, p7zip-full, gnupg-curl, dos2unix, realpath ]
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: HB_CI_THREADS=4
    - os: osx
      osx_image: xcode8.2
      compiler: i686-w64-mingw32-gcc
      env: HB_CI_THREADS=4
before_install:
  - mxepkgs=(
      mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql}
      mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd});
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update > /dev/null;
      brew install p7zip;
      if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
        brew install mingw-w64 jq osslsigncode dos2unix gpg coreutils;
        brew cask install wine-devel;
        ./package/mpkg_win_dl_mxe.sh "${mxepkgs[@]}";
        ./package/mpkg_win_dl_mxe.sh mxe-{i686,x86-64}-w64-mingw32.shared-{jpeg,freetype-bootstrap,fontconfig,libiconv};
      else
        brew install cairo curl freeimage gd ghostscript icu4c libmagic mariadb openssl@1.1 qt5 s-lang unixodbc;
      fi;
    elif [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$CC" = 'i686-w64-mingw32-gcc' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      echo 'deb http://pkg.mxe.cc/repos/apt/debian wheezy main' | sudo tee /etc/apt/sources.list.d/mxeapt.list > /dev/null;
      sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB;
      sudo dpkg --add-architecture i386;
      sudo apt-get update;
      sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install wine "${mxepkgs[@]}";
    fi;
script:
  - if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
        export PATH="/Applications/Wine Devel.app/Contents/Resources/wine/bin:${PATH}";
        export DISPLAY=:88.0; wineboot;
      fi;
      if ./package/mpkg_win_ci.sh && [ "${TRAVIS_BRANCH#*prod*}" = "${TRAVIS_BRANCH}" ] ; then
        mv -f harbour-snapshot-win.7z "harbour-snapshot-win-built-on-${TRAVIS_OS_NAME}.7z";
      fi;
    else
      ls -lA "$(dirname "$(which "${CC}${HB_CCSUFFIX}")")/${CC}"*;
      "${CC}${HB_CCSUFFIX}" -v;
      HB_COMPILER=$CC make -j "${HB_CI_THREADS}";
    fi;
deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: harbour-snapshot-win-built-on-${TRAVIS_OS_NAME}.7z
  file_glob: false
  tag_name: v3.4.0dev
  draft: false
  prerelease: true
  overwrite: true
  on:
    branch: master
    condition: "$CC = i686-w64-mingw32-gcc"
notifications:
  email: false
git:
  submodules: false
  depth: 10
