language: c
compiler:
 - clang
 - gcc
env:
  matrix:
    - HB_COMPILER=clang
    - HB_COMPILER=gcc
script: make
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -m firebird2.1-dev
 - sudo apt-get install -qq -m liballegro4.2-dev
 - sudo apt-get install -qq -m libcairo2-dev
 - sudo apt-get install -qq -m libcups2-dev
 - sudo apt-get install -qq -m libcurl4-openssl-dev
 - sudo apt-get install -qq -m libfreeimage-dev
 - sudo apt-get install -qq -m libgd2-xpm-dev
 - sudo apt-get install -qq -m libgpm-dev
 - sudo apt-get install -qq -m libgs-dev
 - sudo apt-get install -qq -m libmagic-dev
 - sudo apt-get install -qq -m libmysqlclient15-dev
 - sudo apt-get install -qq -m libncurses-dev
 - sudo apt-get install -qq -m libpq-dev
 - sudo apt-get install -qq -m libslang2-dev
 - sudo apt-get install -qq -m unixodbc-dev
notifications:
 email: false
git:
 submodules: false
