notifications:
  email: false
git:
  depth: 10
os: osx

before_install:
  - time travis_retry brew update > /dev/null
  - time travis_retry brew install --force-bottle --build-bottle wine
  - DISPLAY=:0 WINEDEBUG=trace+all WINEPREFIX="${HOME}/.wine" time wineboot --init

script:
  - echo Done.
