notifications:
  email: false
git:
  depth: 10
os: osx

before_install:
  - time travis_retry brew update > /dev/null
  - time travis_retry brew install --force-bottle --build-bottle wine
# - time travis_retry brew install wine
  - # export DISPLAY=:0
  - # export WINEPREFIX="${HOME}/.wine"
  - time wineboot --init

script:
  - echo Done!
