branches:
  only:
  - master
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
  - i686-w64-mingw32-gcc
  - x86_64-w64-mingw32-gcc
matrix:
    exclude:
        - os: osx
          compiler: i686-w64-mingw32-gcc
        - os: osx
          compiler: x86_64-w64-mingw32-gcc
sudo: false
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5
      - g++-5
      - firebird2.5-dev
     #- liballegro4.2-dev
      - libcairo2-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libfreeimage-dev
      - libgd2-xpm-dev
      - libgpm-dev
     #- libgs-dev
      - libicu-dev
      - libmagic-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpq-dev
     #- libslang2-dev
      - unixodbc-dev
      - binutils-mingw-w64
      - gcc-mingw-w64
      - wine
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update > /dev/null;
       brew install cairo;
       brew install curl;
       brew install freeimage;
       brew install gd;
       brew install ghostscript;
       brew install icu4c;
       brew install libmagic;
       brew install mariadb;
       brew install openssl;
       brew install s-lang;
       brew install unixodbc;
    fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       if   [ "$CC" = "i686-w64-mingw32-gcc" ] ; then
          export HB_COMPILER=gcc && make HB_BUILD_CONTRIBS=no;
          export HB_CCPREFIX=i686-w64-mingw32-;
          export HB_PLATFORM=win;
          export CC=mingw;
          export HB_BUILD_3RDEXT=no;
          export HB_BUILD_VERBOSE=yes;
          ls -lA /usr/bin/${HB_CCPREFIX}*;
       elif [ "$CC" = "x86_64-w64-mingw32-gcc" ] ; then
          export HB_COMPILER=gcc && make HB_BUILD_CONTRIBS=no;
          export HB_CCPREFIX=x86_64-w64-mingw32-;
          export HB_PLATFORM=win;
          export CC=mingw64;
          export HB_BUILD_3RDEXT=no;
          export HB_BUILD_VERBOSE=yes;
          ls -lA /usr/bin/${HB_CCPREFIX}*;
       elif [ "$CC" = "gcc" ] ; then
          export HB_CCSUFFIX=-5;
          ls -lA /usr/bin/gcc*;
       else
          export HB_CCSUFFIX=-3.7;
          ls -lA /usr/bin/clang*;
       fi;
    fi
  - export HB_COMPILER=$CC && make
notifications:
  email: false
git:
  submodules: false
