# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
language: c
env:
  - HB_CI_THREADS=4
os:
  - linux
  - osx
osx_image: xcode8.2
compiler:
  - clang
  - gcc
  - i686-w64-mingw32-gcc
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
          source:
            - llvm-toolchain-precise-3.8
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
  exclude:
    - os: osx
      compiler: gcc
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - firebird2.5-dev
     #- libcairo2-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libfreeimage-dev
      - libgd2-xpm-dev
      - libgpm-dev
     #- libgs-dev
      - libicu-dev
      - libmagic-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpq-dev
     #- libslang2-dev
      - unixodbc-dev
      - binutils-mingw-w64
      - gcc-mingw-w64
      - wine
      - p7zip-full
before_install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update > /dev/null;
      brew install p7zip;
      if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
        brew install mingw-w64 jq osslsigncode dos2unix gpg coreutils;
        brew cask install wine-devel;
      else
        brew install cairo;
        brew install curl;
        brew install freeimage;
        brew install gd;
        brew install ghostscript;
        brew install icu4c;
        brew install libmagic;
        brew install mariadb;
        brew install openssl@1.1;
        brew install qt5;
        brew install s-lang;
        brew install unixodbc;
      fi;
    fi
script:
  - if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
        export PATH="/Applications/Wine Devel.app/Contents/Resources/wine/bin:${PATH}";
        export DISPLAY=:88.0; wineboot;
      fi;
      ./package/mpkg_win_ci.sh;
      mv -f harbour-snapshot-win.7z "harbour-snapshot-win-built-on-${TRAVIS_OS_NAME}.7z";
    else
      if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
        if [ "$CC" = 'gcc' ]; then
          export HB_CCSUFFIX=-6;
        else
          export HB_CCSUFFIX=-3.8;
        fi;
        export HB_USER_CFLAGS="${HB_USER_CFLAGS} -fstack-protector-strong";
      fi;
      export HB_USER_CFLAGS="${HB_USER_CFLAGS} -D_FORTIFY_SOURCE=2";
      ls -lA "$(dirname "$(which "${CC}${HB_CCSUFFIX}")")/${CC}"*;
      "${CC}${HB_CCSUFFIX}" -v;
      export HB_COMPILER=$CC && make -j "$HB_CI_THREADS";
    fi;
deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: harbour-snapshot-win-built-on-${TRAVIS_OS_NAME}.7z
  prerelease: true
  overwrite: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = osx && $CC = i686-w64-mingw32-gcc"
notifications:
  email: false
git:
  submodules: false
  depth: 10
