branches:
  only:
  - master
  - test_travis
language: c
env:
  - HB_CI_THREADS=4
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
  - cross-windows
matrix:
  exclude:
    - os: osx
      compiler: cross-windows
sudo: false
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5
      - g++-5
      - firebird2.5-dev
     #- liballegro4.2-dev
      - libcairo2-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libfreeimage-dev
      - libgd2-xpm-dev
      - libgpm-dev
     #- libgs-dev
      - libicu-dev
      - libmagic-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpq-dev
     #- libslang2-dev
      - unixodbc-dev
      - binutils-mingw-w64
      - gcc-mingw-w64
      - wine
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update > /dev/null;
       brew install cairo;
       brew install curl;
       brew install freeimage;
       brew install gd;
       brew install ghostscript;
       brew install icu4c;
       brew install libmagic;
       brew install mariadb;
       brew install openssl;
       brew install s-lang;
       brew install unixodbc;
    fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       if [ "$CC" = "cross-windows" ] ; then
          export HB_COMPILER=clang && make -j $HB_CI_THREADS HB_BUILD_DYN=no HB_BUILD_CONTRIBS=no;
          export HB_BUILD_3RDEXT=no;
          export HB_PLATFORM=win;
          export HB_CCPREFIX=i686-w64-mingw32-;
          ls -lA /usr/bin/${HB_CCPREFIX}*;
          export HB_COMPILER=mingw && make -j $HB_CI_THREADS;
          wine ./bin/${HB_PLATFORM}/${HB_COMPILER}/harbour.exe -build;
          export HB_CCPREFIX=x86_64-w64-mingw32-;
          ls -lA /usr/bin/${HB_CCPREFIX}*;
          export HB_COMPILER=mingw64 && make -j $HB_CI_THREADS;
          wine ./bin/${HB_PLATFORM}/${HB_COMPILER}/harbour.exe -build;
       elif [ "$CC" = "gcc" ] ; then
          export HB_CCSUFFIX=-5;
          ls -lA /usr/bin/gcc*;
          export HB_COMPILER=$CC && make -j $HB_CI_THREADS;
       else
          export HB_CCSUFFIX=-3.7;
          ls -lA /usr/bin/clang*;
          export HB_COMPILER=$CC && make -j $HB_CI_THREADS;
       fi;
    else
       export HB_COMPILER=$CC && make -j $HB_CI_THREADS;
    fi
notifications:
  email: false
git:
  submodules: false
