branches:
  only:
  - master
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
    - gcc-5
    - g++-5
    - firebird2.5-dev
    - libcairo2-dev
    - libcurl4-openssl-dev
    - libfreeimage-dev
    - libgd2-xpm-dev
    - libgpm-dev
    - libmagic-dev
    - libmysqlclient-dev
    - libncurses5-dev
    - libpq-dev
    - unixodbc-dev
script: export HB_COMPILER=$CC && make
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ "$CC" = "gcc" ]; then
         export HB_CCSUFFIX=-5;
         ls -lA /usr/bin/gcc*;
      fi;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew install allegro;
      brew install cairo;
      brew install curl;
      brew install freeimage;
      brew install gd;
      brew install ghostscript;
      brew install libmagic;
      brew install mariadb;
      brew install ncurses;
      brew install postgresql;
      brew install unixodbc;
    fi
notifications:
  email: false
git:
  submodules: false
