version: 3.4.{build}
branches:
  only:
  - master
skip_tags: true
clone_depth: 8
clone_folder: C:\hb
environment:
  matrix:
  - TARGET: msvc64
  - TARGET: msvc
# - TARGET: mingw64
  - TARGET: mingw
install:
- md C:\nsis\
- curl -sS -L https://unsis.googlecode.com/files/nsis-2.46.5-Unicode-setup.exe -o C:\nsis\setup.exe
- 7z x -oC:\nsis\ C:\nsis\setup.exe > nul
- xcopy /q /s /y C:\nsis\$_OUTDIR C:\nsis\Contrib\Graphics\
# Long url: https://downloads.sourceforge.net/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-posix/sjlj/x86_64-4.9.2-release-posix-sjlj-rt_v4-rev2.7z
- curl -sS -L https://bit.ly/1EDA3Hy -o mingw.7z
# Will unpack into C:\mingw64\
- 7z x -oC:\ mingw.7z > nul
build_script:
- set HB_DIR_MINGW=C:\mingw64\
- set HB_DIR_NSIS=C:\nsis\
- if "%TARGET:~0,5%" == "mingw" set PATH=%HB_DIR_MINGW%bin;%PATH%
# Required only for the default mingw distro in C:\mingw\
#- if "%TARGET%" == "mingw" set HBWIN_NO_WINHTTP_H=yes
- if "%TARGET%" == "mingw" set HB_CPU=x86
- if "%TARGET%" == "mingw64" set HB_CPU=x86_64
- if "%TARGET%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
- if "%TARGET%" == "msvc64" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
- if "%TARGET:~0,4%" == "msvc" set _HB_MSVC_ANALYZE=no
- set HB_BUILD_STRIP=bin
- set HB_BUILD_DYN=no
- set HB_BUILD_CONTRIB_DYN=no
- set HB_BUILD_PKG=yes
- set HB_BUILD_POSTRUN=hbtest hbspeed
- win-make.exe clean install
