version: 3.4.{build}
branches:
  only:
  - master
skip_tags: true
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\hb\
environment:
  HB_VF: daily
  matrix:
# Do not set HB_COMPILER here, it will prevent compiler version auto-detection.
# - TARGET: msvc64
# - TARGET: msvc
# - TARGET: mingw64
  - TARGET: mingw
    BINTRAY_APIKEY:
      secure: ZrOhbhL3M2mVTZu+MU2WPDB/4rJArq4rEdND/eKa9iNHFCiLNUF49jvfbuXfnCGE
    BINTRAY_USER:
      secure: jfLq1ApyVLNouxv07skhrg==
    BINTRAY_PATH:
      secure: +CyA1IIhoPpI7EY54BsRADDxb1V62HDWLSekCX4mTxk=
install:
- set VER_CURL=7.43.0
- set VER_OPENSSL=1.0.2d
- mkdir C:\w\
- curl -fsS https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/s/se/sevenzip/7-Zip/9.20/7za920.zip -o 7z.7z
- openssl dgst -sha256 7z.7z | findstr /i /c:"2a3afe19c180f8373fa02ff00254d5394fec0349f5804e0ad2f6067854ff28ac"
- 7z x -y -oC:\w\7z 7z.7z > nul
- curl -fsS http://7zsfx.info/files/7zsd_150_2712.7z -o 7zsfx.7z
- openssl dgst -sha256 7zsfx.7z | findstr /i /c:"e5a2a05997553cde6318149951da1e449b0fd277a6e671ac06bfde8572754739"
- 7z x -y -oC:\w\7zsfx 7zsfx.7z > nul
- curl -fsS -L --proto-redir =https https://fossies.org/windows/misc/upx391w.zip -o upx.zip
- openssl dgst -sha256 upx.zip | findstr /i /c:"d7d4817f46d2616c209c46fb8bce44e4bec93ab5adef5e4dfc93ee879527be1b"
- 7z e -y -oC:\w\upx upx.zip > nul
# Long URL: "https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/m/mi/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.1.0/threads-win32/sjlj/x86_64-5.1.0-release-win32-sjlj-rt_v4-rev0.7z" https://goo.gl/HF6raX
# Long URL: "https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/m/mi/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.1.0/threads-posix/sjlj/x86_64-5.1.0-release-posix-sjlj-rt_v4-rev0.7z"
- curl -fsS -L --proto-redir =https https://goo.gl/kS5jx4 -o mingw.7z
- openssl dgst -sha256 mingw.7z | findstr /i /c:"65b30e0469f03d0e219a1ebe022f135692ed6ecdaf4f9a86923ece7689157244"
# Will unpack into C:\mingw64\
- 7z x -y -oC:\w\ mingw.7z > nul
- curl -fsS -L --proto-redir =https https://dl.bintray.com/vszakats/generic/curl-%VER_CURL%-win32-mingw.zip -o curl-win-mingw.zip
- openssl dgst -sha256 curl-win-mingw.zip | findstr /i /c:"6a631f893fcf8d6b0f0494579b15cfc443c8c16be184ffdbbdff02c77ab24101"
- 7z x -y -oC:\w\ curl-win-mingw.zip > nul
- curl -fsS -L --proto-redir =https https://dl.bintray.com/vszakats/generic/curl-%VER_CURL%-win64-mingw.zip -o curl-win-mingw64.zip
- openssl dgst -sha256 curl-win-mingw64.zip | findstr /i /c:"b8b4a2eff402bf2d79878baf628ee6e7d53c78c254dd95a52c8469a08fce528e"
- 7z x -y -oC:\w\ curl-win-mingw64.zip > nul
- curl -fsS -L --proto-redir =https https://dl.bintray.com/vszakats/generic/openssl-%VER_OPENSSL%-win32-mingw.zip -o openssl-win-mingw.zip
- openssl dgst -sha256 openssl-win-mingw.zip | findstr /i /c:"d6be98b4e6f3c83a1a57fb89936ac41d89b8244e416c7dc672e79fec03c9ff03"
- 7z x -y -oC:\w\ openssl-win-mingw.zip > nul
- curl -fsS -L --proto-redir =https https://dl.bintray.com/vszakats/generic/openssl-%VER_OPENSSL%-win64-mingw.zip -o openssl-win-mingw64.zip
- openssl dgst -sha256 openssl-win-mingw64.zip | findstr /i /c:"13dcc5c8675ffa2aabf7f73b7e200684e9e7246b294207c84b1e7e9683d1a7d2"
- 7z x -y -oC:\w\ openssl-win-mingw64.zip > nul
build_script:
- set HB_SFX_7Z=C:\w\7zsfx\7zsd.sfx
- set HB_DIR_7Z=C:\w\7z\
- set HB_DIR_UPX=C:\w\upx\
- set HB_DIR_MINGW=C:\w\mingw64
- if "%TARGET:~0,5%" == "mingw" set PATH=%HB_DIR_MINGW%\bin;%PATH%
- if "%TARGET%" == "mingw" set HB_CPU=x86
- if "%TARGET%" == "mingw64" set HB_CPU=x86_64
- if "%TARGET%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
- if "%TARGET%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
- if "%TARGET%" == "msvc64" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
- if "%TARGET%" == "msvc64" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
#- if "%TARGET:~0,4%" == "msvc" set _HB_MSVC_ANALYZE=yes
- if "%TARGET%" == "mingw" set HB_WITH_CURL=C:\w\curl-%VER_CURL%-win32-mingw\include
- if "%TARGET%" == "mingw" set HB_WITH_OPENSSL=C:\w\openssl-%VER_OPENSSL%-win32-mingw\include
#- if "%TARGET%" == "mingw" set HB_WITH_QT=C:\w\Qt\5.4\mingw491_32\include
- if "%TARGET%" == "mingw64" set HB_WITH_CURL=C:\w\curl-%VER_CURL%-win64-mingw\include
- if "%TARGET%" == "mingw64" set HB_WITH_OPENSSL=C:\w\openssl-%VER_OPENSSL%-win64-mingw\include
#- if "%TARGET%" == "msvc" set HB_WITH_QT=C:\w\Qt\5.4\msvc2013_64_opengl\include
#- if "%TARGET%" == "msvc64" set HB_WITH_QT=C:\w\Qt\5.4\msvc2013_64_opengl\include
- if "%TARGET:~0,5%-%HB_BUILD_MODE%" == "mingw-cpp" set HB_USER_LDFLAGS=-static-libgcc -static-libstdc++
#- set HB_WITH_ADS=C:\w\ads\acesdk
#- set HB_WITH_CAIRO=C:\w\cairo\include\cairo
#- set HB_WITH_FIREBIRD=C:\w\firebird\include
#- set HB_WITH_FREEIMAGE=C:\w\freeimage\Dist
#- set HB_WITH_GD=C:\w\gd\include
#- set HB_WITH_MYSQL=C:\w\mariadb\include\mysql
#- set HB_WITH_OCILIB=C:\w\ocilib\include
#- set HB_WITH_PGSQL=C:\w\pgsql\include
#- set HB_BUILD_CONTRIBS=no
- set HB_INSTALL_3RDDYN=yes
- set HB_BUILD_STRIP=bin
- set HB_BUILD_DYN=no
- set HB_BUILD_CONTRIB_DYN=yes
- set HB_BUILD_OPTIM=yes
- set HB_BUILD_PKG=yes
- set HB_BUILD_POSTRUN=hbtest
- rem "hbspeed --stdout"
- set _HB_BUILD_PKG_ARCHIVE=no
- set _HB_PKG_BUNDLE_C=no
#- set _HB_PKG_DEBUG=yes
- win-make.exe clean install HB_VERSION=%HB_VF%
deploy_script:
- call package\mpkg_win.bat
- curl -fsS -u "%BINTRAY_USER%:%BINTRAY_APIKEY%" -X PUT "https://api.bintray.com/content/%BINTRAY_PATH%/3.4.0dev/harbour-daily-win.7z.exe?override=1&publish=1" --data-binary @harbour-daily-win.7z.exe
