repo_slug: vszakats/harbour-core
site_slug: vszakats/harbour-core
site_branch_and_root: master/docs/
dl_url: https://github.com/vszakats/harbour-core/releases
badge_version: "3.4"

sample_categories:
  - basic
  - arrays
  - database
  - extensions
  - web
collections:
  samples:
    output: true
defaults:
  - scope:
      path: ""
      type: samples
    values:
      layout: sample
      _topdir: ../

incremental: true
exclude: ["node_modules"]
sass:
  style: compressed
